### ISSUE TITLE
UX: JSON document textarea should be collapsible or moved

### ISSUE THREAD

**Issue by jamesrom** [tidwall/gjson-play#2]
If you have a moderately sized JSON document you must scroll down to see the results. It goes without saying this harms the live-edit nature of the tool.

A couple of potential solutions:

1. Move the query textbox directly above the output textbox
2. Make the document textarea collapsible
3. Set a max size to the document textarea and add a scrollbar

**Comment by nilsocket** [comment]
Same case here, I need to scroll to bottom of the page, each and every-time to check the results.

It is also hard to find, the difference between json data and json results.
i.e., it is hard to find where json data ends and where results start, as it is long document.

Thank you.

**Comment by tidwall** [comment]
I made the text boxes vertically static. Hopefully it works better now.

**Comment by nilsocket** [comment]
Thanks a lot, it fixes my problem.
